
[workspace]

members = [
	
	"cycles-bank",

	"cts",
    "cycles_transferrer",
    "cycles_market",

    "users_map_canister",
    "user_canister",

    "cts_lib",
    "global_allocator_counter",

    
]



exclude = [
    "scripts",
    "canister1",


]



[profile.release]
