[package]
name = "cts"
version = "0.1.0"
authors = ["levi <levifeldman37@gmail.com>"]
edition = "2021"


[lib]
crate-type = ["cdylib"]

[dependencies]
cts_lib = { path = "../../cts_lib" }
candid = "0.7.11"
futures = "0.3.21"
serde = "1.0.137"
serde_cbor = "0.11.2"
base64 = "0.13.0"


