[package]
name = "cts"
version = "0.1.0"
authors = ["levi <levifeldman37@gmail.com>"]
edition = "2021"


[lib]
crate-type = ["cdylib"]

[dependencies]
cts_lib = { path = "../../cts_lib" }
candid = "0.8.3"
futures = "0.3.23"
serde = "1.0.137"
serde_cbor = "0.11.2" # change for the ciborium = "0.2.0"
serde_bytes = "0.11.6"
base64 = "0.13.0"
sha2 = "0.9.1"
num-traits = "0.2.15"
