[package]
name = "cm_main"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]


[dependencies]
cts_lib = { path = "../../../cts_lib" }
candid = "0.8.4"
serde = "1.0.137"
futures = "0.3.23"
serde_bytes = "0.11.6"
ic-stable-structures = "0.5.3"
