[package]
name = "cts_lib"
version = "0.1.0"
edition = "2021"



[dependencies]
ic-cdk = "0.6.8"
ic-cdk-macros = "0.6.8"
ic-certified-map = "0.3.0"
ic-ledger-types = "0.2.0"
candid = "0.8.3"
sha2 = "0.9.1"
serde = "1.0.137"
serde_bytes = "0.11.6"
