[package]
name = "cts_lib"
version = "0.1.0"
edition = "2021"



[dependencies]
ic-cdk = "0.5.1"
ic-cdk-macros = "0.5.1"
ic-certified-map = { git = "https://github.com/dfinity/cdk-rs", rev = "129d1a8c595525c6f4c54e73bafa779143e568ce" }
ic-ledger-types = "0.1.1"
sha2 = "0.9.1"
candid = "0.7.11"
serde = "1.0.136"
