[package]
name = "users_map_canister"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]


[dependencies]
cts_lib = { path = "../../cts_lib" }
serde = "1.0.137"
candid = "0.7.16"
futures = "0.3.23"
serde_bytes = "0.11.6"
