
[workspace]
resolver = "2"

members = [
    "cts_lib",
    "canisters/cts",
    "canisters/cbs_map",
    "canisters/cycles_bank",
    "canisters/cycles_transferrer",
    "canisters/cycles_market/cm_main",
    "canisters/cycles_market/cm_tc",
    "canisters/cycles_market/cm_storage_lib",
    "canisters/cycles_market/cm_trades_storage",
    "canisters/cycles_market/cm_positions_storage",
    "canisters/cycles_market/cm_caller",
    "canister_authorizations",
]

exclude = [
        
]

[profile.release]
lto = true
opt-level = 'z'          
codegen-units = 1 
split-debuginfo= "packed"
strip = "debuginfo"
debug = false


[workspace.dependencies]
ic-cdk = "0.10.0"
ic-certified-map = { git = "https://github.com/levifeldman/cdk-rs.git", rev = "212b8c34ec17f849a256feedac9003c26a38e84b" } 
ic-ledger-types = "0.7.0"
candid = "0.9.5"
sha2 = "0.9.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_bytes = "0.11.6"
icrc-ledger-types = { git = "https://github.com/cycles-transfer-station/ic.git", rev = "c74ce7317761e540d722d01fa6c26a046707f372" }
ic-stable-structures = "0.5.3"
rmp-serde = "1.1.1"
futures = "0.3.23"
num-traits = "0.2.15"


