
[workspace]

members = [
    "cts_lib",
    "canisters/cts",
    "canisters/cbs_map",
    "canisters/cycles_bank",
    "canisters/cycles_transferrer",
    "canisters/cycles_market/cm_main",
    "canisters/cycles_market/cm_icrc1token_trade_contract",
    "canisters/cycles_market/cm_icrc1token_trade_log_storage",
    "canisters/cycles_market/cm_caller",
]

exclude = [
        
]

[profile.release]
lto = true
opt-level = 'z'          
codegen-units = 1 
split-debuginfo= "packed"
strip = "debuginfo"
debug = false


[workspace.dependencies]
ic-cdk = { git = "https://github.com/dfinity/cdk-rs.git", rev = "24bdf5ee37399c4e27ad329880c79733f6454f27" } #"0.10.0" #
ic-certified-map = { git = "https://github.com/levifeldman/cdk-rs.git", rev = "5a8a90c1734b2802e2166ce14e73df75aac61a22" } # "0.3.0"
ic-ledger-types = "0.2.0"
candid = "0.8.4"
sha2 = "0.9.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_bytes = "0.11.6"
icrc-ledger-types = { git = "https://github.com/dfinity/ic.git", rev = "949407ea4a43cac19444e6da8f0ac08153946fbb" }
#ic-icrc1-client-cdk = { git = "https://github.com/dfinity/ic.git", rev = "290eabafc91fb37b89f64bcd98c6907d3e0ee405" }
#ic-icrc1 = { git = "https://github.com/dfinity/ic.git", rev = "290eabafc91fb37b89f64bcd98c6907d3e0ee405" }
ic-stable-structures = "0.5.3"
rmp-serde = "1.1.1"
futures = "0.3.23"
num-traits = "0.2.15"


