
[workspace]

members = [
    "cts_lib",
    "canisters/cts",
    "canisters/users_map_canister",
    "canisters/user_canister",
    "canisters/cycles_transferrer",
    "canisters/cycles_market",
    
    "canisters/testcanister1",
    "canisters/testcanister2",
]



