
[workspace]

members = [
    "cts_lib",
    "canisters/cts",
    "canisters/cbs_map",
    "canisters/cycles_bank",
    "canisters/cycles_transferrer",
    "canisters/cycles_market",
    
]

exclude = [
    "canisters/testcanister1",
    "canisters/testcanister2",
        
]



[profile.release]
lto = true
opt-level = 'z'
#codegen-units = 1 


