[package]
name = "testcanister1"
version = "0.1.0"
edition = "2021"





[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = { path = "../../../../../DFINITY/cdk-rs/src/ic-cdk" }
ic-cdk-macros = "0.5.5" #{ path = "../../../../../DFINITY/cdk-rs/src/ic-cdk" }
candid = "0.7.11"
serde = "1"
