[package]
name = "cycles_bank"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]


[dependencies]
cts_lib = { path = "../../cts_lib" }
serde = "1.0.137"
candid = "0.8.4"
futures = "0.3.23"
